// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import Experience from './Experience/index.svelte';
import Hero from './Hero/index.svelte';
import Projects from './Projects/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	biography: Biography,
	experience: Experience,
	hero: Hero,
	projects: Projects,
	rich_text: RichText
};
